name: firebase_auth_rest
description: A platform independent Dart/Flutter Wrapper for the Firebase
  Authentication API based on REST
version: 2.0.3
homepage: https://github.com/Skycoder42/firebase_auth_rest

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.4
  coverage: ^1.1.0
  dart_pre_commit: ^5.1.0+1
  dart_test_tools: ^4.9.0
  freezed: ^2.3.4
  json_serializable: ^6.1.5
  meta: ^1.7.0
  mocktail: ^0.3.0
  test: ^1.20.1
  tuple: ^2.0.0
